# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell
sudo: enabled

cache:
  directories:
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"

cabal: head
matrix:
  include:
  - ghc: "8.6.5"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  - ghc: "8.4.4"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --system-ghc --test --no-run-tests

script:
 - stack test
