language: haskell
sudo: enabled
services:
  - docker
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
cabal: head
env:
  global:
    - STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    - BIN="$TRAVIS_BUILD_DIR/bin"

ghc: 
  - "8.6.5"

install:
- curl -sSL https://get.haskellstack.org/ | sh
- stack --version
script:
- bash script/deploy
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/guiguzi
