language: ruby
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/guiguzi .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/guiguzi

script:
  - echo hello

