resolver: nightly-2019-07-30
packages:
- base-dto
- base-web
- base-client
- base-database
- base-redis
- base-main
- opentracing
extra-deps:
- salak-0.3.2
- git: https://github.com/leptonyu/boots.git
  commit: f14f93e2354eee3bf1c27fe54e7fe728f3c4ec6a
nix:
  packages:
  - zlib
  - lzma
  - postgresql
