resolver: nightly-2019-08-02
packages:
- base-dto
- base-web
- base-client
- base-database
- base-redis
- base-main
- opentracing
- consul
extra-deps:
- git: https://github.com/leptonyu/boots.git
  commit: 26976ae4098afb0bfe625529c230b35c7a73c883
- salak-0.3.3
- salak-yaml-0.3.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
