resolver: nightly-2019-08-07
packages:
- base-web
- base-client
- base-database
- base-redis
- base-rabbitmq
- base-main
- opentracing
- consul
- main
- captcha
extra-deps:
- boots-app-0.1.0.3
- hs-captcha-1.0
nix:
  packages:
  - zlib
  - lzma
  - postgresql
  - gd
  - fontconfig
  - freetype
  - libpng
  - libjpeg
