resolver: nightly-2019-08-02
packages:
- base-dto
- base-web
- base-client
- base-database
- base-redis
- base-main
- opentracing
- consul
extra-deps:
- git: https://github.com/leptonyu/boots.git
  commit: db0bba482a13fd845e8f9593c4399589db924c13
- salak-0.3.3
- salak-yaml-0.3.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
