resolver: nightly-2019-09-02
packages:
- base/base-database
- base/base-redis
- base/base-rabbitmq
# - main
# - captcha

- captcha-api
- captcha-server

# - ../boots/boots
# - ../boots/boots-app
# - ../boots/boots-web
# - ../boots/boots-cloud

extra-deps:
- git: https://github.com/leptonyu/captcha.git
  commit: e25151454aeada025502306498ef26b98587ae0b
- git: https://github.com/leptonyu/boots.git
  commit: 94035839b77f0f1e3a175a9b36aa3555da1e3efc
  subdirs:
  - boots
  - boots-app
  - boots-web
  - boots-cloud
- warp-3.3.0
- http2-2.0.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
