resolver: nightly-2019-08-07
packages:
- base/base-web
- base/base-client
- base/base-database
- base/base-redis
- base/base-rabbitmq
- base/base-main
- third/opentracing
- third/consul
- main
- captcha
extra-deps:
- git: https://github.com/leptonyu/boots.git
  commit: 1bfe82f31783fbd47f50a6987227ddfa433dd999
  subdirs:
  - boots-app
nix:
  packages:
  - zlib
  - lzma
  - postgresql
