resolver: nightly-2019-08-26
packages:
- base/base-database
- base/base-redis
- base/base-rabbitmq
- main
- captcha

extra-deps:
- git: https://github.com/leptonyu/boots.git
  commit: 448c5b994949d5790d523c623248244e9970f5cb
  subdirs:
  - boots
  - boots-app
  - boots-web
  - boots-cloud
- warp-3.3.0
- http2-2.0.3
- salak-0.3.5.3
- salak-yaml-0.3.5.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
