resolver: nightly-2019-09-04
packages:
- base/base-database
- base/base-redis
- base/base-rabbitmq
# - main
# - captcha

- captcha-api
- captcha-server

extra-deps:
- git: https://github.com/leptonyu/captcha.git
  commit: bad8a4f2a7e49a9fce3d39867eabd3a704a6ddea
# - git: https://github.com/leptonyu/boots.git
#   commit: 94035839b77f0f1e3a175a9b36aa3555da1e3efc
#   subdirs:
#   - boots
#   - boots-app
#   - boots-web
#   - boots-cloud
- boots-app-0.2.0.1
- boots-web-0.2.0.1
- boots-cloud-0.2
- warp-3.3.0
- http2-2.0.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
