resolver: nightly-2019-08-07
packages:
- base/base-web
- base/base-client
- base/base-database
- base/base-redis
- base/base-rabbitmq
- base/base-main
- third/opentracing
- third/consul
- main
- captcha
extra-deps:
- boots-0.1.1
- boots-app-0.1.1
- salak-0.3.5.1
- salak-yaml-0.3.5.1
- warp-3.3.0
- http2-2.0.3
nix:
  packages:
  - zlib
  - lzma
  - postgresql
