resolver: nightly-2019-08-06
packages:
- base-web
- base-client
- base-database
- base-redis
- base-rabbitmq
- base-main
- opentracing
- consul
- main
extra-deps:
- boots-0.1
- boots-app-0.1.0.3
- salak-0.3.3.1
nix:
  packages:
  - zlib
  - lzma
  - postgresql
