resolver: nightly-2019-08-06
packages:
- base-web
- base-client
- base-database
- base-redis
- base-rabbitmq
- base-main
- opentracing
- consul
extra-deps:
- boots-0.1
- boots-app-0.1.0.3
- git: https://github.com/leptonyu/salak.git
  commit: d6a449996650a62e9b66850add8c15083674001d
  subdirs:
  - salak
nix:
  packages:
  - zlib
  - lzma
  - postgresql
