_common: !include "../common.yaml"
name:                main
<<: *legal

dependencies:
  - base >= 4.11 && < 5

executables:
  guiguzi:
    source-dirs:      .
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    main: Main.hs
    dependencies:
    - base-redis
    - boots-app
    - boots-web
    - boots-cloud
    - servant-server
    - captcha