_common: !include "../common.yaml"
name:                base-redis
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots
  - salak
  - microlens
  - data-default
  - hedis


library:
  source-dirs: src
  exposed-modules:
  - Base.Redis
