_common: !include "../../common.yaml"
name:                base-client
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots-app
  - salak
  - microlens
  - data-default
  - http-client


library:
  source-dirs: src
  exposed-modules:
  - Base.Client
