_common: !include "../common.yaml"
name:                opentracing
<<: *legal

dependencies:
  - base >= 4.10 && < 5
  - bytestring
  - scientific
  - text
  - unordered-containers
  - microlens
  - time

default-extensions:
  - GeneralizedNewtypeDeriving
  - RecordWildCards
  - ScopedTypeVariables

library:
  source-dirs: src
  exposed-modules:
  - Data.Opentracing
  other-modules:
  - Data.Opentracing.Types
  - Data.Opentracing.Tracer