_common: !include "../common.yaml"
name:                captcha
<<: *legal
extra-source-files:
- cn.ttf

dependencies:
  - base >= 4.11 && < 5
  - aeson
  - base-redis
  - base64-bytestring
  - boots-app
  - boots-web
  - bytestring
  - file-embed-lzma
  - FontyFruity
  - hedis
  - http-types
  - JuicyPixels
  - microlens
  - Rasterific
  - servant-server
  - servant-swagger
  - splitmix
  - swagger2
  - text
  - wai

library:
  source-dirs: src
  exposed-modules:
  - Data.Captcha
  - Data.Captcha.Internal
