_common: !include "../common.yaml"
name:                captcha
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - hs-captcha
  - servant-server
  - servant-swagger
  - base-web
  - boots-app
  - wai

library:
  source-dirs: src
  exposed-modules:
  - Data.Captcha
