_common: !include "../common.yaml"
name:                captcha
<<: *legal
extra-source-files:
- cn.ttf

dependencies:
  - base >= 4.11 && < 5
  - servant-server
  - servant-swagger
  - base-web
  - boots-app
  - wai
  - http-types
  - swagger2
  - microlens
  - text
  - aeson
  - base64-bytestring
  - base-redis
  - hedis
  - bytestring
  - JuicyPixels
  - Rasterific
  - FontyFruity
  - splitmix
  - file-embed-lzma

library:
  source-dirs: src
  exposed-modules:
  - Data.Captcha
  - Data.Captcha.Internal
