_common: !include "../../common.yaml"
name:                base-database
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots-app
  - boots-web
  - bytestring
  - microlens
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-sqlite
  - resource-pool
  - salak
  - text
  - unliftio-core


library:
  source-dirs: src
  exposed-modules:
  - Base.Database
