_common: !include "../../common.yaml"
name:                base-rabbitmq
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - amqp
  - boots-app
  - network
  - salak


library:
  source-dirs: src
  exposed-modules:
  - Base.Rabbitmq
