_common: !include "../../common.yaml"
name:                base-redis
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots-app
  - boots-web
  - hedis
  - salak


library:
  source-dirs: src
  exposed-modules:
  - Base.Redis
