_common: !include "../common.yaml"
name:                base-main
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots
  - wai
  - salak
  - data-default
  - servant-server
  - microlens
  - base-web
  - base-database

library:
  source-dirs: src
  exposed-modules:
  - Base.Main