_common: !include "../common.yaml"
name:                base-main
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots-app
  - servant-server
  - microlens
  - mtl
  - base-web
  - base-client

library:
  source-dirs: src
  exposed-modules:
  - Base.Env
  - Base.Main