_common: !include "../common.yaml"
name:                consul
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - servant-client
  - servant
  - servant-swagger
  - swagger2
  - http-client
  - unordered-containers
  - text
  - salak
  - base-client
  - microlens
  - aeson
  - boots
  - base-dto
  - mtl

library:
  source-dirs: src
  exposed-modules:
  - Network.Consul
