_common: !include "../common.yaml"
name:                base-dto
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - text
  - microlens


library:
  source-dirs: src
  exposed-modules:
  - Base.Dto
