_common: !include "../common.yaml"
name:                base-web
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots
  - wai
  - salak
  - data-default
  - servant-server
  - microlens
  - text
  - servant-swagger
  - servant-swagger-ui
  - mtl
  - reflection
  - swagger2
  - unordered-containers
  - aeson
  - vault
  - opentracing
  - http-types
  - warp
  - exceptions
  - base-dto


library:
  source-dirs: src
  exposed-modules:
  - Base.Web
  - Base.Health
  - Base.Actuator
  
  other-modules:
  - Base.Web.Types
  
  - Base.Middleware.Actuator
  - Base.Middleware.Trace

  - Base.Actuator.Health
  - Base.Actuator.Refresh
  - Base.Actuator.Info
    
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
