_common: !include "../../common.yaml"
name:                base-web
<<: *legal

dependencies:
  - base >= 4.11 && < 5
  - boots-app
  - wai
  - salak
  - data-default
  - servant-server
  - microlens
  - text
  - servant-swagger
  - servant-swagger-ui-jensoleg
  - mtl
  - reflection
  - swagger2
  - unordered-containers
  - aeson
  - vault
  - opentracing
  - http-types
  - warp
  - exceptions
  - base-client
  - consul
  - ekg-core
  - monad-logger


library:
  source-dirs: src
  exposed-modules:
  - Base.Web
  - Base.Health
  - Base.Actuator
  - Base.Metrics
  
  other-modules:
  - Base.Web.Types
  - Base.Web.Swagger
  
  - Base.Middleware.Actuator
  - Base.Middleware.Trace
  - Base.Middleware.Error 
  - Base.Middleware.Consul
  
  - Base.Actuator.Metrics
  - Base.Actuator.Health
  - Base.Actuator.Refresh
  - Base.Actuator.Info
  - Base.Actuator.Logger
    
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
